name: SwiftApi
description: A plugin that exposes bukkit functionality over an Apache Thrift interface
main: org.phybros.minecraft.SwiftApiPlugin
version: 1.2
website: http://dev.bukkit.org/server-mods/swiftapi
author: phybros