/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.phybros.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Represents various map environment types that a world may be
 */
public enum Environment implements org.apache.thrift.TEnum {
  NETHER(0),
  NORMAL(1),
  THE_END(2);

  private final int value;

  private Environment(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Environment findByValue(int value) { 
    switch (value) {
      case 0:
        return NETHER;
      case 1:
        return NORMAL;
      case 2:
        return THE_END;
      default:
        return null;
    }
  }
}
