/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package nl.radic.swiftapi.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Valid game modes
 */
public enum GameMode implements org.apache.thrift.TEnum {
  /**
   * Survival Mode
   */
  SURVIVAL(0),
  /**
   * Creative Mode
   */
  CREATIVE(1),
  /**
   * Adventure Mode
   */
  ADVENTURE(2),
  SPECTATOR(3);

  private final int value;

  private GameMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GameMode findByValue(int value) { 
    switch (value) {
      case 0:
        return SURVIVAL;
      case 1:
        return CREATIVE;
      case 2:
        return ADVENTURE;
      case 3:
        return SPECTATOR;
      default:
        return null;
    }
  }
}
